version: '3.8'
services:
  api:
    container_name: myapp_api
    # image: thomas-oliver/nestjs-dockerized
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MYSQL_DATABASE=users_api
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp
    ports:
      - '5000:3000'
    links:
      - mysql
    depends_on:
      - mysql

  mysql: # Example Service
    container_name: myapp_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=users_api
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:

networks:
  default:
    external:
      name: myapp
